name: Build sample Java Maven project

on: [push, pull_request]

jobs:
  compile:
    # compile job

  build:
    runs-on: ubuntu-20.04
    needs: compile
    name: Build the Maven Project
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
          path: ~/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
           ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
    - name: Build and test project
      working-directory: java-maven
      run: mvn -B verify
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact.jar
        path: java-mavenen/target/java-maven.jar
