name: Build sample Java Maven project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Build the Maven Project
       uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
     - name: Build and test project
       run: mvn -B verify
     - name: Upload Maven build artifact
       uses: actions/upload-artifact@v2
       with:
        name: artifact.jar
        path: ${{ working-directory }}/target/my-app-1.0-SNAPSHOT.jar
